[font]
  normal = { family = "Hack Nerd Font", style = "Regular" }
  size = 16.0

[env]
  WINIT_X11_SCALE_FACTOR = "1.5"

[window]
  dimensions = { columns = 80, lines = 30 }

[terminal.shell]
    program = "/bin/zsh"

[[keyboard.bindings]]
    key = "NumpadEnter"
    chars = "\r"
