#!/usr/bin/env bash

set -e

OHMYZSH_DIR=~/.oh-my-zsh

if [ -d "$OHMYZSH_DIR" ]; then
    rm -f ~/.zshrc
    ln -s "$(pwd)/.zshrc" ~/.zshrc
else
    echo "please install oh-my-zsh"
fi

rm -f ~/.gitconfig
ln -s "$(pwd)/.gitconfig" ~/.gitconfig

rm -f ~/biome.json
ln -s "$(pwd)/biome.json" ~/biome.json
