[tasks]
hello = "echo 'Hello from mise'"

[env]
_.file = ".env"
SHELL = "/bin/zsh"

[tool_alias]
m = "mise"

[tools]
go = "latest"
bun = "latest"
deno = "latest"
node = "latest"
python = "latest"
rust = "latest"
usage = "latest"
watchexec = "latest"
awscli = { version = "latest", symlink_bins = "true" }
ripgrep = "latest"
fzf = "latest"
gitleaks = "latest"
lazygit = "latest"
lazydocker = "latest"
"aqua:jorgerojas26/lazysql" = "latest"
