#!/usr/bin/env bash

set -e

rm -f ~/.gemini/settings.json
ln -s "$(pwd)/settings.json" ~/.gemini/settings.json

rm -f ~/.gemini/skills
ln -s "$(pwd)/skills" ~/.gemini/skills

rm -f ~/.gemini/GEMINI.md
ln -s "$(pwd)/GEMINI.md" ~/.gemini/GEMINI.md
