#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/ ~/Desktop/code ~/Desktop/code/approva/ ~/Desktop/code/approva/A@Back ~/Desktop/code/approva/A@Back/A@layers  ~/Downloads -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

cd "$selected" || return